"""Helpers to compare science calendar XML output between rework and legacy implementations.

This module provides utilities for comparing the XML science calendars generated
by the reworked scheduler against those from the legacy implementation. It handles
running both implementations, capturing their outputs, and performing detailed
comparisons to identify any differences.

Key functions:
    - compare_with_legacy: Run both implementations and compare XML outputs
    - ComparisonResult: Dataclass containing comparison outcomes
"""

from __future__ import annotations

import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

from pandorascheduler_rework import observation_utils, science_calendar


@dataclass(frozen=True)
class ComparisonResult:
    """Outcome of a rework vs legacy XML comparison.
    
    Attributes
    ----------
    match
        True if the XML outputs match exactly, False otherwise.
    legacy_xml
        The XML content generated by the legacy implementation.
    rework_xml
        The XML content generated by the rework implementation.
    diff
        Unified diff string showing differences between the outputs.
        Empty string if outputs match.
    """

    match: bool
    legacy_xml: str
    rework_xml: str
    diff: str


def compare_with_legacy(
    *,
    legacy_package_dir: Optional[Path] = None,
    schedule_filename: str = "Pandora_Schedule_0.8_0.0_0.2_2026-02-05_to_2027-02-05.csv",
    python_executable: str = sys.executable,
    extra_pythonpath: Optional[Iterable[str]] = None,
    schedule_csv_path: Optional[Path] = None,
) -> ComparisonResult:
    """Run the legacy generator and the rework builder and compare their outputs.

    Parameters
    ----------
    legacy_package_dir
        Path to the legacy :mod:`pandorascheduler` package root.  Defaults to the
        repository copy under ``src/pandorascheduler``.
    schedule_filename
        CSV schedule filename relative to ``legacy_package_dir / "data"`` that
        the generators should consume.
    python_executable
        Python interpreter used to execute the legacy script.  Defaults to the
        interpreter running the rework code.
    extra_pythonpath
        Iterable of paths appended to the ``PYTHONPATH`` when executing the
        legacy script.  Used to provide dependencies to the legacy code.
    schedule_csv_path
        Optional override for the schedule CSV path.  When set, uses this file
        directly instead of looking for ``schedule_filename`` in the legacy data dir.

    Returns
    -------
    ComparisonResult
        Contains both XML outputs, diff text, and match status.
    """

    script_dir = Path(__file__).resolve().parent
    if legacy_package_dir is None:
        legacy_package_dir = script_dir.parent / "pandorascheduler"

    data_dir = legacy_package_dir / "data"
    if not data_dir.is_dir():
        raise FileNotFoundError(f"Legacy data directory not found: {data_dir}")

    schedule_csv = schedule_csv_path or (data_dir / schedule_filename)
    if not schedule_csv.exists():
        raise FileNotFoundError(f"Schedule CSV not found: {schedule_csv}")

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        legacy_xml = tmp_path / "legacy.xml"
        rework_xml = tmp_path / "rework.xml"

        env = os.environ.copy()
        if extra_pythonpath:
            pythonpath_items = list(extra_pythonpath)
            if "PYTHONPATH" in env:
                pythonpath_items.append(env["PYTHONPATH"])
            env["PYTHONPATH"] = os.pathsep.join(pythonpath_items)

        legacy_script = legacy_package_dir / "sched2xml_WIP.py"
        if not legacy_script.exists():
            raise FileNotFoundError(f"Legacy script not found: {legacy_script}")

        subprocess.run(
            [python_executable, str(legacy_script)],
            env=env,
            cwd=legacy_package_dir,
            check=True,
            capture_output=True,
        )

        legacy_default_xml = data_dir / "Pandora_science_calendar.xml"
        if not legacy_default_xml.exists():
            raise FileNotFoundError(
                f"Legacy did not produce expected output: {legacy_default_xml}"
            )
        shutil.copy(legacy_default_xml, legacy_xml)

        inputs = science_calendar.ScienceCalendarInputs(
            schedule_csv=schedule_csv,
            data_dir=data_dir,
        )
        science_calendar.generate_science_calendar(inputs, output_path=rework_xml)

        legacy_content = legacy_xml.read_text(encoding="utf-8")
        rework_content = rework_xml.read_text(encoding="utf-8")

        legacy_normalized = _normalize_xml(legacy_content)
        rework_normalized = _normalize_xml(rework_content)

        if legacy_normalized == rework_normalized:
            return ComparisonResult(
                match=True,
                legacy_xml=legacy_content,
                rework_xml=rework_content,
                diff="",
            )

        diff_lines = list(
            difflib.unified_diff(
                legacy_normalized.splitlines(keepends=True),
                rework_normalized.splitlines(keepends=True),
                fromfile="legacy",
                tofile="rework",
            )
        )

        return ComparisonResult(
            match=False,
            legacy_xml=legacy_content,
            rework_xml=rework_content,
            diff="".join(diff_lines),
        )


def _normalize_xml(content: str) -> str:
    """Normalize XML for comparison by removing insignificant whitespace."""
    lines = content.splitlines()
    stripped = [line.strip() for line in lines]
    return "\n".join(line for line in stripped if line)


__all__ = ["compare_with_legacy", "ComparisonResult"]
